### PR TITLE
Unset PYTHONPATH in run_regress when calling flight starcheck

### PR DESCRIPTION
**Pull request by jeanconn**
Unset PYTHONPATH in run_regress when calling flight starcheck

### CODE REVIEW

**Comment by jeanconn** [comment]
This should probably just go in 11.12, but I didn't want to presume.

**Comment by taldcroft** [comment]
I thought you would put this into #158 in order to facilitate testing.  Or was that what you meant by 11.12?

**Comment by jeanconn** [comment]
Yeah, I wasn't sure if I should just push to your PR at this point.  I'll
close this PR then and just push the commit to #158.

**Comment by taldcroft** [comment]
You own this now.  :smile:

**Comment by jeanconn** [comment]
Change put into #158

**Pull request closed without merging**
