### PR TITLE
Tighten star mag limits when CCD temps warmer than -14

### PR DESCRIPTION
**Pull request by jeanconn**
Tom proposes:

decrease mag limits by 0.15 for each 1 C increase above -14 C

### CODE REVIEW

**Comment by taldcroft** [comment]
As far as code goes this looks fine.  I think it would be worth discussing this with SSAWG before actually merging though.

Also, I was wondering if it might be enlightening to run the regression tests for recent years *without* the additional dynamic mag limits line in the output in order to get a cleaner idea of the diffs in yellow and red star warnings.

**Comment by taldcroft** [comment]
I should note that I haven't explicitly verified that the current set of loops in front of the CCD temp. calculation is sufficient for populating the obs structure.  I'm assuming that if you got a good run then that is the case.

**Comment by jeanconn** [comment]
Regarding waiting for SSAWG, are you concerned with the determination of the "scale factor" or the whole idea?

**Comment by jeanconn** [comment]
And yes, I did functionally test this before make a PR.

**Comment by taldcroft** [comment]
Mostly the scale factor and whether we should put in some conservatism.  Of course it has also occurred to me that this approach is quite simplistic and not robust against accumulating radiation damage.  The acquisition probabilities model could help. However, getting something simple in place sooner rather than later is a good thing.

**Comment by jeanconn** [comment]
Maybe I should just do the main "loop" reorganization as a separate PR.  It add the option to use the temperature values in the per-obsid checking, but the implementation of the actual mag scaling should probably be separated out anyway.

**Comment by taldcroft** [comment]
Good idea.

**Comment by jeanconn** [comment]
Reorganization now in #113

**Comment by jeanconn** [comment]
Superceded by work in #119

**Pull request closed without merging**
