### PR TITLE
WIP: Add option to override kadi dynamic state dither with state from file

### PR DESCRIPTION
**Pull request by jeanconn**
Add option to override kadi dynamic state dither with state from file

I've used this for a test run, today, on JUN2716T using this as the dither state file:
```
fido: more jun2716t_dither_state.json
{
    "dither": "DISA",
    "dither_ampl_pitch": 0,
    "dither_ampl_yaw": 0,
    "dither_period_pitch": 0,
    "dither_period_yaw": 0,
    "time": 582574205.235
}
```

For the disable dither state, it doesn't really matter what the dither parameters are (because we generally use an AODITPAR to set explicitly before enabling dither), but these 6 keys should have values to keep Parse_CM_File happy.

### CODE REVIEW

**Comment by taldcroft** [comment]
Looks generally good, but there should probably be some validation that the file has the right keys, and more importantly some docs so that when I need this in 3 years then I'll manage.  Maybe just copying the example file into the `-help` page and also printing an error message if validation fails with that example.

**Comment by jeanconn** [comment]
It looks like for SEP0619B, we ran into a condition where the kadi commanded states dither state didn't match the History
```
Dither status in kadi commands does not match DITHER history
```
And the dither amplitudes were left undefined when passed to proseco to determine P2 values causing a TypeError
```TypeError: unsupported operand type(s) for +: 'NoneType' and 'int' at line 45
 at ./starcheck/src/starcheck.pl line 45.
	main::__ANON__("TypeError: unsupported operand type(s) for +: 'NoneType' and "...) called at (eval 80) line 3
	Ska::Starcheck::Obsid::proseco_probs("__main__", "proseco_probs", HASH(0x4888800)) called at starcheck/src/lib/Ska/Starcheck/Obsid.pm line 2997
	Ska::Starcheck::Obsid::set_proseco_probs_and_check_P2(Ska::Starcheck::Obsid=HASH(0x6de59d0)) called at ./starcheck/src/starcheck.pl line 690
```
Whichever way we decide to go, we should probably configure so either History or kadi commands "wins" and makes some kind of dither states for starcheck to proceed (with big red warnings or whatever).

**Comment by taldcroft** [comment]
I vote for kadi winning, since that is the product that we control for a flight review.  History should become something that is a sanity check but not used in the starcheck review.

**Comment by jeanconn** [comment]
I agree with kadi commanded states winning (or an override dither state from this PR).

**Comment by taldcroft** [comment]
I rebased this.  I used VS code to help with the rebase and it works very well to better visualize the changes and in several cases accept both HEAD and incoming changes.  On the down side it automatically removes trailing white space, generating a lot of unrelated diffs.

**Comment by taldcroft** [comment]
Note in the GitHub diff there is a setting button to remove whitespace diffs. With that, this rebase appears the same as #345.

**Comment by taldcroft** [comment]
Though after all that I would still rather fix this problem correctly instead of putting in a back-door for handling a situation that the flight code (run by SOT MP) should handle.

**Comment by jeanconn** [comment]
I think we should still have an override for weird interrupts.  There are other things that aren't ideal... I assume that the kadi cmds cron job will pick up my update to dither cmds at some point... but what point would that be?  Sometimes we're in a little bit of a hurry.

**Comment by jeanconn** [comment]
And sure, I did not think that rebasing would be a challenge, just looking at the piece of code and having minutes it was cleaner for me to just copy the edits I wanted to make a new branch to represent exactly what I ran for MAY2620B.  I did not really care which one got used and figured I'd just close one or the other.  If you prefer the rebased one that is fine.

**Comment by jeanconn** [comment]
And of course still want tools to do nonload commands for us.  I suppose I need to stop the previous CTI at some point etc...

**Comment by jeanconn** [comment]
PS In our previous discussion, it was "let kadi win".  Do we still want that?  If so, I'm fine with that, though thus far History has been more right than kadi continuity due to my manual edits.  If we set the kadi status to "win",  I'd just want to put a big red warning at the top of starcheck outputs indicating a mismatch with History if that happened (instead of starcheck just dying trying to calculate p_acq on None dither amplitudes).

**Comment by jeanconn** [comment]
This is overcome by events.  With https://github.com/sot/starcheck/pull/390 the kadi state is authoritative and with command states v2 one could use a KADI_SCENARIO for the rare case of needing to set dither to something different for the starcheck.

**Pull request closed without merging**
