### PR TITLE
Safe mode 2018283 prov

### PR DESCRIPTION
**Pull request by jeanconn**
This implements several changes in starcheck to support load review after the 2018283 safe mode:

  - Sets the "fractional" guide count metric to use temperature-scaled magnitude limits for the counting
  - Sets the acquisition probability threshold to more conservative values per Tom's suggested thresholds in memo "ACA planning requirements for loads going forward"
  - Uses the ACA model from 24-Oct-2018 in chandra_models 3.18.1

### CODE REVIEW

**Comment by taldcroft** [comment]
Awesome.  Approved for LR with FD waiver.

**Comment by jeanconn** [comment]
I should mark this with a dev version and tag as well.

**Comment by jeanconn** [comment]
Do we want to just approve the provisional acquisition probability limits for flight starcheck now and make them less conservative in a future release?

**Comment by taldcroft** [comment]
Yes, that makes sense.

**Pull request merged**
