### PR TITLE
Switch to using proseco agasc file as default.

### PR DESCRIPTION
**Pull request by jeanconn**
Switch to using proseco agasc file as default.

### CODE REVIEW

**Comment by jeanconn** [comment]
I'll need to think a bit more on what we might want to do to show this is fine / safe .

**Comment by taldcroft** [comment]
What's the driver?

**Comment by jeanconn** [comment]
Right now, we're using all three (agasc1p7.h5, miniagasc1p7.h5, and proseco_agasc_1p7.h5) inst starcheck.

I'd like to cut down the dependencies from a maintenance perspective; and also I think in the agasc module aren't we building a Dec index for each of these as they are loaded?  So I think it isn't super memory efficient either.

I just noticed it again when working standalone and I thought I had everything I wanted by my ska_sync didn't have the bigger agasc file.

But mostly I put the PR here because I thought it was a good idea for one minute and wanted to capture it.  Didn't necessarily want to push this now.

**Comment by taldcroft** [comment]
Sounds good.  I see no problem in principle with using proseco_agasc everywhere (including in place of miniagasc).

**Pull request merged**
