### PR TITLE
Use get_effective_t_ccd

### PR DESCRIPTION
**Pull request by jeanconn**
Use get_effective_t_ccd

Starcheck needs the effective_t_ccd a bunch of places anyway, so I'm not sure if we win anything by doing the get_aca_catalog transition.  I'll work that in another branch.

Of course, if I'm calling get_effective_t_ccd, the trick is to confirm I'm not accidentally calling it twice on any input temperature.

### CODE REVIEW

**Comment by jeanconn** [comment]
Though all the uglier parts are probably where we need review...

**Comment by taldcroft** [comment]
Just wondering if it is possible to use the `aca` object from `get_aca_catalog` to populate the Obsid object with guide and acq effective temperatures, and then use those where appropriate.  I.e. don't change the low-level helper functions, but have the routines that call them decide which temperature to pass.  This should remove any possibility of double-effectiving because it is never directly called in starcheck.  Then in the info statement just check if t_ccd != t_ccd_eff and issue a statement if so.  That decouples the details of computing effective temperature from the perl code to issue an info statement.

Anyway, having said that, what you have here will work just fine and I'm OK with it.  PITEOG.

**Comment by taldcroft** [comment]
Oh, and if you go with the current approach then I agree you should just close #310.

**Comment by jeanconn** [comment]
Though #310 just moves things in the right direction and could go as well.  It might be a good first step toward working with an ACACatalogTable in starcheck anyway.

**Comment by jeanconn** [comment]
Also, whatever we do what do you think about testing?   I have played both with changing all of the temperatures (just adding 2 degrees in the original assignments) and played with changing the planning limits to something lower to use old schedules.

**Comment by taldcroft** [comment]
That testing is fine.

**Comment by jeanconn** [comment]
I looked more at getting the effective temperatures back from the ACACatalogTable, but given we would like this for this week, I'm thinking of just not fiddling more with changing the API of anything that goes across the Perl / Python divide.  Is this approved for now with the PITEOG in mind?

**Pull request merged**
