### PR TITLE
Characteristics update Mar 2015

### PR DESCRIPTION
**Pull request by jeanconn**
Update starcheck characteristics files including bad pixel and star lists and the ACA xija model spec.

### CODE REVIEW

**Comment by taldcroft** [comment]
:+1:

**Comment by jeanconn** [comment]
Do you want to run with this for Load Review approval for this week?

**Comment by taldcroft** [comment]
Yes, but not the replan load review.

**Comment by jeanconn** [comment]
This brings in the ACA model from https://github.com/sot/chandra_models/pull/11

**Pull request merged**
