### PR TITLE
Handle new DOT trace ids ending in MXXX instead of MTLB

### PR DESCRIPTION
**Pull request by jeanconn**
Handle new DOT trace ids ending in MXXX instead of MTLB

### CODE REVIEW

**Comment by jeanconn** [comment]
It looks like github caught up and I could finally see the branch and make a PR against it.  This PR is informational-only at this point.

**Comment by taldcroft** [comment]
You can guess the all-caps three letter comment I would make and save me from having to type it.  :smile:

**Comment by jeanconn** [comment]
I had a silly idea that this reduced the diff, but agree now that makes no
sense.

**Comment by taldcroft** [comment]
Apparently we agreed to this change a while back and so we will want to run with this change.

**Pull request merged**
