### PR TITLE
Use agasc 1p7 by default

### PR DESCRIPTION
**Pull request by jeanconn**
Switch the default agasc to 1p7.

The switch to use a new AGASC directory looks like it works with a few trivial edits on flight starcheck.

### CODE REVIEW

**Comment by jeanconn** [comment]
This is a keep-in-back-pocket commit, in case we don't get to moving to Python for the star fetching.  In fact the move to Python for star fetching might also come with a Py3 transition in starcheck and we're not quite there yet.

This is also not yet tested with the pure-Perl agasc interface.

**Comment by taldcroft** [comment]
How did you verify that it is picking up AGASC 1.7?

**Comment by jeanconn** [comment]
All I've verified is that it prints out it is using AGASC 1.7.  For a real functional test will probably need to pick out some stars that will have different 1.7 magnitudes and confirm they are right.

**Comment by jeanconn** [comment]
overcome by events

**Pull request closed without merging**
