### PR TITLE
Update checklist for dynamic aimpoint file

### PR DESCRIPTION
**Pull request by jeanconn**
Update checklist for dynamic aimpoint file

### CODE REVIEW

**Comment by jeanconn** [comment]
@taldcroft Does this need SSAWG review before we present at load review?

**Comment by taldcroft** [comment]
> Does this need SSAWG review before we present at load review?

Why don't you just send an informational note to ssawg and give anyone the chance to comment prior to the next load review.

**Comment by jeanconn** [comment]
Is your plan for freezing characteristics just to stop the update job?  If so I probably need to do something with "ACA 047: Characteristics file is no more than 30 days old" too.

**Comment by taldcroft** [comment]
Yes that needs to be retired.

**Comment by jeanconn** [comment]
How should deprecated items work?  Do we modify the 047 entry to say 'no
longer needed' or just cut it?

**Comment by taldcroft** [comment]
Cut.

**Pull request merged**
