### PR TITLE
Delete some unused code and stop parsing SOE

### LINKED ISSUE #168: Is FigureOfMerit::star_probs just decorative at this point?
I think that star_probs at

https://github.com/sot/starcheck/blob/f5b9602af68db4cd0a605a93f3dddeebb28368b4/src/lib/Ska/Starcheck/FigureOfMerit.pm#L97

isn't actually called at all now that we're using the acquisition model.

### LINKED ISSUE #200: Stop parsing SOE
I don't think we've needed the SOE since we deprecated Chex, but it is still being parsed:

https://github.com/sot/starcheck/blob/3bea225e291a1eebccc9f05a9e92f2f3ae1c4c5a/starcheck/src/starcheck.pl#L280

### PR DESCRIPTION
**Pull request by jeanconn**
Delete some unused code.   Stops parsing SOE (with checklist update).

Closes #200
Closes #168

### CODE REVIEW

**Comment by jeanconn** [comment]
Regarding "there must still be code that outputs the header output line", I'm pretty sure that's just a output from `get_file` so cutting the call to get_file
```
 -my $soe_file   = get_file("$par{dir}/mps/soe/ms*.soe", 'SOE');
```
cuts that output written at

https://github.com/sot/starcheck/blob/4b7099f1c1dcd13d4dcc1d3615e6397cec07affc/starcheck/src/starcheck.pl#L1204

But of course will do a new grep.

**Comment by taldcroft** [comment]
Ah I just looked at the code and the output happens here:

https://github.com/sot/starcheck/blob/4b7099f1c1dcd13d4dcc1d3615e6397cec07affc/starcheck/src/starcheck.pl#L674

Of course the part that confused me is that `get_files` updates a global dict `input_files` which then gets used in report generation, with keys being sorted.  This is why we write new code in Python and work for code that is explicit.

**Comment by jeanconn** [comment]
Ah yes.  I forgot about that one.  But yes `get_files` does half of its work as "side effects"!

**Comment by jeanconn** [comment]
Also, happy to do the update to remove the SOE from the checklist in this PR; good idea.

**Comment by jeanconn** [comment]
```
ska-fido: grep -iR soe starcheck
starcheck/src/aca_load_review_cl.rst:  - SOE: ./mps/soe/msddd:hhvv.soe
starcheck/src/lib/Ska/Parse_CM_File.pm:sub SOE {
starcheck/src/lib/Ska/Parse_CM_File.pm:    my    $soe_file = shift;
starcheck/src/lib/Ska/Parse_CM_File.pm:# Taken from RAC's code /proj/sot/ska/ops/soe/soeA.pl
starcheck/src/lib/Ska/Parse_CM_File.pm:# read the SOE record formats into the hashes of lists $fld and $len
starcheck/src/lib/Ska/Parse_CM_File.pm:# read the SOE file from STDIN into $soe
starcheck/src/lib/Ska/Parse_CM_File.pm:    open my $SOE, $soe_file or die "Couldn't open SOE file '$soe_file'\n";
starcheck/src/lib/Ska/Parse_CM_File.pm:    my $soe = (<$SOE>);
starcheck/src/lib/Ska/Parse_CM_File.pm:    my $l = length $soe;
starcheck/src/lib/Ska/Parse_CM_File.pm:# unpack the SOE file
starcheck/src/lib/Ska/Parse_CM_File.pm:    my %SOE;
starcheck/src/lib/Ska/Parse_CM_File.pm:	my $typ = substr $soe,$p,3;
starcheck/src/lib/Ska/Parse_CM_File.pm:	    my $rec = substr $soe,$p,$rlen{$typ};
starcheck/src/lib/Ska/Parse_CM_File.pm:		    $SOE{$obsid}{$rflds[$i]} = $rvals[$i];
starcheck/src/lib/Ska/Parse_CM_File.pm:	    die "Parse_CM_File::SOE: Cannot identify record of type $typ\n ";
starcheck/src/lib/Ska/Parse_CM_File.pm:    return %SOE;
starcheck/src/lib/Ska/Parse_CM_File.pm:# define the structure of SOE file records:
```

So the soe shows up in the load review checklist, and in the soe parsing routine in Ska::Parse_CM_File  .  We could cut the routine there as well.

**Pull request merged**
