### PR TITLE
Add end of maneuver date/time to output for obsid

### PR DESCRIPTION
**Pull request by jeanconn**
Add end of maneuver date/time to output for obsid

These are the commits that were approved and merged as #190 , but it looks like *this* is exactly where my accidental force push to master overwrote the record of that merge ever happening.  Redoing the PR seems the best way to proceed.

### CODE REVIEW

**Comment by jeanconn** [comment]
I'm not sure if I restored the previous branch if it would let me "re"merge, but for 4 commits it doesn't seem critical to experiment with github that way.

**Comment by taldcroft** [comment]
Do we want to disallow force push to master for starcheck?

**Comment by jeanconn** [comment]
Yes.

**Comment by jeanconn** [comment]
​I just set "master" as a protected branch and also checked the box to
apply that to adminstrators.​

**Pull request merged**
